services:
  admin:
    build:
      context: .
      secrets: [npm_token]
    ports: ['3002:3002']
    environment:
      NUXT_PUBLIC_ADMIN_API_BASE: ${NUXT_PUBLIC_ADMIN_API_BASE:-http://localhost:5201}

secrets:
  npm_token:
    environment: NODE_AUTH_TOKEN
