<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../L2.Admin.Configurations/L2.Admin.Configurations.csproj" />
    <ProjectReference Include="../L2.Admin.Contracts/L2.Admin.Contracts.csproj" />
    <ProjectReference Include="../L2.Admin.Repositories.Interfaces/L2.Admin.Repositories.Interfaces.csproj" />
  </ItemGroup>
</Project>
